# Generated by Django 4.2.10 on 2024-03-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(choices=[(0, 'No category selected'), (1, 'Chicken'), (2, 'Pork'), (3, 'Beef'), (4, 'Fish'), (4, 'Vegetarian')], default=0),
        ),
    ]
