# Generated by Django 4.2.10 on 2024-03-14 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_book', '0005_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(choices=[(0, 'No category selected'), (1, 'Chicken'), (2, 'Pork'), (3, 'Beef'), (4, 'Fish'), (5, 'Vegetarian')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'recipe')},
        ),
    ]
