# Generated by Django 4.2.10 on 2024-04-01 14:55

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0007_alter_favourite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1200, message='The text must not exceed 1200 characters.')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(help_text="Please only use the built in formatter. Don't copy paste!", validators=[django.core.validators.MinLengthValidator(100, message='The text must be at least 100 characters.'), django.core.validators.MaxLengthValidator(5000, message='The text must not exceed 5000 characters.')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='feature_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', help_text='Image dimension 3:2 will work best.', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text="Please only use the built in formatter. Don't copy paste!", validators=[django.core.validators.MinLengthValidator(10, message='The text must be at least 10 characters.'), django.core.validators.MaxLengthValidator(2500, message='The text must not exceed 2500 characters.')]),
        ),
    ]
